[package]
name = "web"
bin-package = "web"
lib-package = "web"

[build]
output-name = "web"

[[build.assets]]
source = "style"
dest = "/"

[server]
site-root = "target/site"
site-pkg-dir = "pkg"
site-addr = "0.0.0.0:3000"
reload-port = 3001