[package]
name = "space_cms_shared"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
leptos = { workspace = true, optional = true }
chrono = { workspace = true }

[features]
default = []
hydrate = ["leptos/hydrate"]
ssr = ["leptos/ssr"]